### ISSUE TITLE
Application wont start after entering Orthanc HTTP settings and restarting.

### ISSUE THREAD

**Issue by ranasrule** [salimkanoun/Orthanc_Tools#2]
Application wont start after entering Orthanc HTTP settings and restarting.

**Comment by salimkanoun** [comment]
Did you restarted the app ? 
What settings did your enter ?

**Comment by salimkanoun** [comment]
Can you give me a capture of your settings input ?

**Comment by ranasrule** [comment]
its possible I entered the wrong settings but still the app should make the user aware of that

**Comment by salimkanoun** [comment]
yes it maybe a parsing problem.
I need to check what do you enter in parameter so I can check your input string.

Can you make a screen capture of your input ? You can send me privatey on salim.kanoun@gmail.com

**Comment by ranasrule** [comment]
I cant send a screen capture as the application wont open.Is there any way to reset the settings ?

**Comment by salimkanoun** [comment]
That's strage it shouldn't stop prevent the app to start.

Could you : 

Test the RC5 version I uploaded (this one should display the error connexion message)

Tell me what you have put in the settings by looking at the registery  
Go to Regedit => HKEY_CURRENT_USER > Software > JavaSoft > prefs > <unnamed> > queryPlugin
Add tell me what you have in ip / port / password  / username

**Comment by ranasrule** [comment]
please see attached screenshot

![untitled](https://user-images.githubusercontent.com/5023419/38258390-c4ff265a-377b-11e8-8961-25bc1eddea62.png)

**Comment by salimkanoun** [comment]
OK got it i'm going to fix !

**Comment by salimkanoun** [comment]
I uploaded RC6, it should fix your problem.
You were missing http:// 
But now it should start giving you an error code and the setup will ask for http:// to accept the orthanc adress
